repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-merge-conflict

  - repo: local
    hooks:
      - id: sqlfluff-lint
        name: sqlfluff-lint
        language: system
        entry: sqlfluff lint
        args: [--dialect, snowflake]
        types: [sql]
        pass_filenames: true

      - id: sqlfluff-fix
        name: sqlfluff-fix
        language: system
        entry: sqlfluff fix
        args: [--dialect, snowflake, --force]
        types: [sql]
        pass_filenames: true
